### ISSUE TITLE
FileNotFoundException using your sample app

### ISSUE THREAD

**Issue by dekenless** [Microsoft/Lumia-imaging-sdk#3]
Exception thrown in StorageFileImageSource in the EditShowcase sample when trying to open an image.  Error is in routine: 

 public Task LoadPhotoAsync(StorageFile file)
        {
            return m_renderer.LoadPhotoAsync(new StorageFileImageSource(file));
        }

System.IO.FileNotFoundException was unhandled by user code
  HResult=-2147024770
  Message=The specified module could not be found. (Exception from HRESULT: 0x8007007E)
  Source=mscorlib
  StackTrace:
       at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
       at Lumia.Imaging.StorageFileImageSource..ctor(IStorageFile storageFile)
       at Lumia.Imaging.EditShowcase.ViewModels.FilterExplorerViewModel.LoadPhotoAsync(StorageFile file)
       at Lumia.Imaging.EditShowcase.ViewModels.FilterExplorerViewModel.<OnBrowseForImage>d__49.MoveNext()
  InnerException:

**Comment by atkulp** [comment]
This is a duplicate of issue #2 .  It's not just me!

**Comment by atkulp** [comment]
Are you still getting this issue?  What version of VS, phone, OS, etc. are you using?  Microsoft says they can't repro the issue so we need to do some digging ourselves!

**Comment by arjunkr21** [comment]
Hi,
Even i had the same issue, but was able to resolve by changing the Application's Target Version. Hope this helps.

![lumiasdk_issue_targetversion](https://cloud.githubusercontent.com/assets/13864595/13103308/7f03abb2-d57b-11e5-9c5f-9bb8038be8d0.jpg)
